### PR TITLE
Add Buildkite CI.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
Failure here looks like https://github.com/rr-debugger/rr/issues/3175, but https://github.com/rr-debugger/rr/pull/3178 isn't part of an `rr` release yet.

@Keno How do you manage the rr version you're building in rr_jll? The latest stable version plus some patches of yours? Should we add the above for CI here?

**Comment by maleadt** [comment]
Actually, that commit is part of our rr fork, and the CPU being requested is in range...

**Comment by Keno** [comment]
Are you trying to replay a trace you got from somewhere else? On AMD CPUs, the CPU number that was used for recording must be available for replay. Also CPUID needs to match exactly, unless the (non-upstreamed) kernel patch I have is in use, in which case the requirement is that the CPUID of the replayer is a superset of the CPUID of the recorder.

**Comment by maleadt** [comment]
No, these are traces being recorded and replayed by CI, so on the very same machine.

**Comment by Keno** [comment]
Since you're streaming it over http, is it possible it accidentally picked it up from a different container running on the same loopback interface? Otherwise I don't understand the failure mode at all. Regardless, the error is during replay and the rr issues you linked are record related, so if this is indeed an rr issue, it is something different.

**Comment by maleadt** [comment]
> Since you're streaming it over http, is it possible it accidentally picked it up from a different container running on the same loopback interface?

Oops, yes that's very likely.

**Pull request merged**
